### ISSUE TITLE
Ta bort söksträngen när man byter språk (eller sakområde?)

### ISSUE THREAD

**Issue by majsan** [majsan/tolkordlistor#16]

**Comment by MalinAhlberg** [comment]
Nu har jag klurat på det här, och jag tror kanske inte att man vill ta bort söksträngen när man byter sakområde. Säg att man söker efter "katt" i socialord, och inte får någon träff, då vill man lägga till sakområdet "djur", och om då blir man arg om en sökord är borta och man måste skriva om det.

Byter man språk är det mer oklart, om man råkar söka efter "porkkana", inte får någon träff och inser att det är för att man sökt på fel språk, då kanske man vill ha kvar söksträngen vid språkbyte?

I karpfrontenden tas söksträngen bort vid byte av sökfält, vilket på sätt och vis är logiskt, men jag vet att det vållar en del irritation ändå, för att man ofta vill söka efter samma sträng men i ett annat fält.

**Comment by majsan** [comment]
Vi väljer att inte göra något tillsvidare.
