### ISSUE TITLE
Anpassa APIet till att det finns flera lexikon

### ISSUE THREAD

**Issue by majsan** [majsan/tolkordlistor#26]
Förslag, man skickar endast med lexikonnamn överallt:

- `/publish/omsorg?lexicon=term-swefin`
- `//search?q=&subtypes=socialord&lang=sv&lexicon=term-swefin`

etc.

**Comment by MalinAhlberg** [comment]
- `/publish/omsorg?mode=term-swefin`
- `/search?q=&subtypes=socialord&lang=sv&mode=term-swefin`

Ska funka fran och med commit:
https://bitbucket.org/Ahlmal/tolkordlistor/commits/fd3d8b7353e57ae8cbdea2b3c466c6dbd79884ca

Man måste uppdatera sin configs och sedan börja med att publicera sakomradena pa nytt.
