### ISSUE TITLE
Sökning på ej publicerat sakområde ger 500 (istället för 401?)

### ISSUE THREAD

**Issue by MalinAhlberg** [majsan/tolkordlistor#34]
https://ws.spraakbanken.gu.se/ws/tolkordlistor/search?q=r&subtypes=gymnasieprogram&lang=fi

**Comment by evali1** [comment]
(Få denna felkod att skriva texten 'område ej tillgängligt' eller så?)

**Comment by MalinAhlberg** [comment]
Ger nu:
`400 Bad Request`

`{"error": "Search failed. Subtype(s) gymnasieprogram not public"}`
