### ISSUE TITLE
Sökning inuti ord

### ISSUE THREAD

**Issue by MalinAhlberg** [majsan/tolkordlistor#36]
Kunna söka på "skola" och få träff på tex "förskola".

**Problem**: sökning på tex 'a' i  socialordlistan kommer ge för många träffar för tex mobiltelefoner.

- [x] lägg till i APIt
- [x] funktionalitet i backend
- [x] parameter i url:en (frontend)
- [x] checkbox i gränssnittet
- [x] hantera jättemånga träffar (backend)
- [x] säga att alla träffar inte visas (frontend)

**Comment by MalinAhlberg** [comment]
### API
`?contains=true`

Exempel: `curl 'localhost:4000/search?q=missbruk&subtypes=socialord&contains=true'`

### För många träffar (backend)
Flagga: `overflow`

Svar: 
```json
{
  "result": [...],
  "overflow": true
}
```

**Comment by majsan** [comment]
Klart!
