### ISSUE TITLE
publiceringssidan -- https://spraakbanken.gu.se/tolkordlistor/publicera/

### ISSUE THREAD

**Issue by Gurras** [majsan/tolkordlistor#37]
1) Det finns ett tomt sakområde att publicera. Är det tomt eller skrivs inte sakområdesnamnet ut?
2) När man publicerar ett område åker det upp i listan, det är kanske bra, men när man avpublicerar åker det längst ner. Åtminstone det sista är ganska förvirrande.

**Comment by majsan** [comment]
2. Jag har gjort en ny issue för enbart det felet (#45)

1. Det är ett sakområde som är tomt, som man kan se här https://ws.spraakbanken.gu.se/ws/tolkordlistor/subtypes?mode=term-swefin&unpublished=true . Kanske @MalinAhlberg vet mer?

**Comment by evali1** [comment]
Det är nog det tomma sakområde som lades till av en bugg som ska vara fixad nu sa @MalinAhlberg, men det går inte att ta bort det från redigeringsgränssnittet - så ta gärna bort den! ... tror jag - om det inte blir problem med ord som läggs in provisoriskt som del i arbetsprocess och inte har fått sakområde än...!

**Comment by MalinAhlberg** [comment]
Ja, precis som Eva säger kommer de från den tidigare buggen. Vi tar bort dem under dagen. Säg till om det dyker upp nya, för det ska det inte göra.

**Comment by MalinAhlberg** [comment]
Obs att det kan komma nya tomma sakområden under dagen, pga en bugg som vi inte har möjlighet att fixa förrän i em/kväll.

**Comment by MalinAhlberg** [comment]
Nu är tomma sakområden borta ur listningen.
 I karp finns bara ett ord med tomt sakområde kvar ("partinamn" <https://spraakbanken.gu.se/karp/#?mode=term-swefin&lang=swe&advanced=false&hpp=25&extended=and%7Csubtype%7Cexists&page=1&search=extended%7C%7Cand%7Csubtype%7Cexists%7C%7Cand%7Csubtype%7Cequals%7C> som inte har någon annan tillhörighet).
