### ISSUE TITLE
sökordet försvinner om man väljer sakområde/språk efter att ha skrivit söksträng

### ISSUE THREAD

**Issue by Gurras** [majsan/tolkordlistor#39]
Eller om det möjligtvis är jag som inte förstår hur man backar till den tidigare vyn efter sakområdesval ...

**Comment by majsan** [comment]
För att stänga sakområdesväljaren så klickar man utanför den eller på knappen igen.

Jag lyckas inte återskapa att sökordet försvinner. Kan du beskriva mer ingående vad du gör när det händer?

**Comment by Gurras** [comment]
Hmm, inte jag heller, jag trodde ni hade gjort nåt åt det … Jaja, den buggen verkar vi kunna stänga. Om jag inte bara var klumpig så får jag snarare vända till chrome och klaga …

**Comment by majsan** [comment]
Okej! Jag stänger.
