### ISSUE TITLE
Hemknapp

### ISSUE THREAD

**Issue by MalinAhlberg** [majsan/tolkordlistor#41]
märker att jag ville klicka på nåt som är 'hem' för att få fatt i översta URL-noden; kan ju vara bra också när det finns varsin + gemensam ingång till Fi och Jiddisch!

**Comment by majsan** [comment]
Vi kan göra rubriken klickbar så att man återställer alla val och kommer tillbaka till https://spraakbanken.gu.se/tolkordlistor
