### ISSUE TITLE
Mellanslag

### ISSUE THREAD

**Issue by MalinAhlberg** [majsan/tolkordlistor#43]
Mystiska mellanslag har dykt upp före komma på vissa ställen!  Jfr:

![image](https://user-images.githubusercontent.com/1029190/50827928-320c1c80-1340-11e9-9baa-93c64c8023e1.png)

![image](https://user-images.githubusercontent.com/1029190/50827934-3801fd80-1340-11e9-9829-77a2c6c98e66.png)

**Comment by majsan** [comment]
Noterat!

OBS: Just nu är det det enda sättet som jag kan se skillnad på komma inuti wordform-fältet eller komma mellan former. (Kanske är det oviktigt.)

**Comment by majsan** [comment]
Väljer att tolka det som oviktigt! :)

**Comment by majsan** [comment]
Fixat

**Comment by majsan** [comment]
Svårare än vad man kan tro...
