### ISSUE TITLE
sökfält i sakområdeslista

### ISSUE THREAD

**Issue by MalinAhlberg** [majsan/tolkordlistor#49]
Sätt dit en defaulttext, typ "Sök efter sakområde här". Alternativt ta bort sökfältet.

**Comment by majsan** [comment]
Kanske vi kan ha båda? Om man kan få till det så att sökfältet bara dyker upp om det finns mer än ett visst antal sakområden, t.ex. 25.

**Comment by majsan** [comment]
Jag gjorde så att jag tog bort sökfältet om antalet sakområden är mindre än 25. Går lätt att ändra vid behov.
